import { I18n } from "i18n-js";
import { useEffect, useState } from "react";

const translations = {
  en: {
    appTitle: "EchoJournal",
    languageName: "English",
    hello: "Hello, %{name}!",
    fallbackName: "there",
    recentEntries: "Recent Entries",
    loadingRecentEntries: "Loading recent entries...",
    noEntriesYet: "No entries yet.",
    myStats: "My Stats",
    mostUsedType: "Most Used Type",
    entriesThisWeek: "Entries This Week",
    streak: "Streak",
    days: "Days",
    addEntry: "Add Entry",
    editEntry: "Edit Entry",
    saveChanges: "Save Changes",
    createEntry: "Create Entry",
    loadingEntry: "Loading entry...",
    title: "Title",
    type: "Type",
    rating: "Rating",
    date: "Date",
    pickDate: "Pick a date",
    coverImage: "Cover Image",
    uploadFromGallery: "Upload From Gallery",
    noImageSelected: "No image selected yet.",
    myThoughts: "My Thoughts",
    writeThoughts: "Write your thoughts...",
    selectThoughtColor: "Select thought color",
    saving: "Saving...",
    titleRequired: "Title is required.",
    mediaPermissionRequired: "Media library permission is required to upload an image.",
    imageProcessError: "The selected image could not be processed.",
    login: "Login",
    email: "Email",
    password: "Password",
    loggingIn: "Logging in...",
    createAccount: "Create an account",
    register: "Register",
    name: "Name",
    surname: "Surname",
    repeatPassword: "Repeat password",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    passwordNotice: "Password must be at least 8 characters and include uppercase, lowercase, and a number.",
    passwordLength: "Password must be at least 8 characters long.",
    passwordUppercase: "Password must contain at least one uppercase letter.",
    passwordLowercase: "Password must contain at least one lowercase letter.",
    passwordNumber: "Password must contain at least one number.",
    passwordsDoNotMatch: "Passwords do not match.",
    myJournal: "My Journal",
    loadingYourEntries: "Loading your entries...",
    filter: "Filter",
    minRating: "Min Rating:",
    maxRating: "Max Rating:",
    all: "All",
    today: "Today",
    thisMonth: "This Month",
    threeMonths: "3 Months",
    thisYear: "This Year",
    apply: "Apply",
    reset: "Reset",
    searchEntries: "Search entries...",
    loadingEntries: "Loading entries...",
    untitled: "Untitled",
    noNotesYet: "No notes yet.",
    details: "Details",
    deleteEntry: "Delete entry?",
    deleteEntryDescription: "This will permanently remove this entry.",
    cancel: "Cancel",
    delete: "Delete",
    deleting: "Deleting...",
    entryIdMissing: "Entry id is missing.",
    rate: "Rate",
    edit: "Edit",
    userName: "User Name",
    logOut: "Log Out",
    stats: "Stats",
    loadingStats: "Loading stats...",
    loginBeforeProfilePicture: "Please log in before adding a profile picture.",
    profilePicturePermissionRequired: "Media library permission is required to add a profile picture.",
    profilePictureProcessError: "The selected profile picture could not be processed.",
    profilePictureSaveError: "The selected profile picture could not be saved.",
    profileMostUsedEntryType: "Most Used Entry Type",
    profileEntriesAddedThisWeek: "Entries Added This Week",
    profileCurrentStreak: "Current Streak",
    profileLongestStreakEver: "Longest Streak Ever",
    profileAverageRating: "Average Rating",
    profileTotalNumberOfEntries: "Total Number of Entries",
    profileTotalEntriesThisMonth: "Total Entries This Month",
    profileEntriesAddedToday: "Entries Added Today",
    profileMostFrequentlyUsedRating: "Most Frequently Used Rating",
    profileHighestRatedCategory: "Highest Rated Category",
    entryTypeMovie: "Movie",
    entryTypeSeries: "Series",
    entryTypeDocumentary: "Documentary",
    entryTypeAnime: "Anime",
    entryTypeMusic: "Music",
    entryTypePodcast: "Podcast",
    entryTypeConcert: "Concert",
    entryTypeTheatre: "Theatre",
    entryTypeOpera: "Opera",
    entryTypeBallet: "Ballet",
    entryTypeStandUp: "Stand-up",
    entryTypeMatch: "Match",
    entryTypeGaming: "Gaming",
    entryTypeBook: "Book",
    entryTypeBlog: "Blog",
    entryTypeExhibition: "Exhibition",
    entryTypeFestival: "Festival",
    entryTypeOther: "Other",
  },
  tr: {
    appTitle: "EchoJournal",
    languageName: "T\u00fcrk\u00e7e",
    hello: "Merhaba, %{name}!",
    fallbackName: "orada",
    recentEntries: "Son Kay\u0131tlar",
    loadingRecentEntries: "Son kay\u0131tlar y\u00fckleniyor...",
    noEntriesYet: "Hen\u00fcz kay\u0131t yok.",
    myStats: "\u0130statistiklerim",
    mostUsedType: "En \u00c7ok Kullan\u0131lan T\u00fcr",
    entriesThisWeek: "Bu Haftaki Kay\u0131tlar",
    streak: "Seri",
    days: "G\u00fcn",
    addEntry: "Kay\u0131t Ekle",
    editEntry: "Kayd\u0131 D\u00fczenle",
    saveChanges: "De\u011fi\u015fiklikleri Kaydet",
    createEntry: "Kay\u0131t Olu\u015ftur",
    loadingEntry: "Kay\u0131t y\u00fckleniyor...",
    title: "Ba\u015fl\u0131k",
    type: "T\u00fcr",
    rating: "Puan",
    date: "Tarih",
    pickDate: "Tarih se\u00e7",
    coverImage: "Kapak G\u00f6rseli",
    uploadFromGallery: "Galeriden Y\u00fckle",
    noImageSelected: "Hen\u00fcz g\u00f6rsel se\u00e7ilmedi.",
    myThoughts: "D\u00fc\u015f\u00fcncelerim",
    writeThoughts: "D\u00fc\u015f\u00fcncelerini yaz...",
    selectThoughtColor: "D\u00fc\u015f\u00fcnce rengini se\u00e7",
    saving: "Kaydediliyor...",
    titleRequired: "Ba\u015fl\u0131k zorunludur.",
    mediaPermissionRequired: "G\u00f6rsel y\u00fcklemek i\u00e7in medya k\u00fct\u00fcphanesi izni gerekiyor.",
    imageProcessError: "Se\u00e7ilen g\u00f6rsel i\u015flenemedi.",
    login: "Giri\u015f Yap",
    email: "E-posta",
    password: "\u015eifre",
    loggingIn: "Giri\u015f yap\u0131l\u0131yor...",
    createAccount: "Hesap olu\u015ftur",
    register: "Kay\u0131t Ol",
    name: "Ad",
    surname: "Soyad",
    repeatPassword: "\u015eifreyi tekrarla",
    creatingAccount: "Hesap olu\u015fturuluyor...",
    alreadyHaveAccount: "Zaten hesab\u0131n var m\u0131?",
    passwordNotice: "\u015eifre en az 8 karakter olmal\u0131; b\u00fcy\u00fck harf, k\u00fc\u00e7\u00fck harf ve say\u0131 i\u00e7ermelidir.",
    passwordLength: "\u015eifre en az 8 karakter uzunlu\u011funda olmal\u0131d\u0131r.",
    passwordUppercase: "\u015eifre en az bir b\u00fcy\u00fck harf i\u00e7ermelidir.",
    passwordLowercase: "\u015eifre en az bir k\u00fc\u00e7\u00fck harf i\u00e7ermelidir.",
    passwordNumber: "\u015eifre en az bir say\u0131 i\u00e7ermelidir.",
    passwordsDoNotMatch: "\u015eifreler e\u015fle\u015fmiyor.",
    myJournal: "G\u00fcnl\u00fc\u011f\u00fcm",
    loadingYourEntries: "Kay\u0131tlar\u0131n y\u00fckleniyor...",
    filter: "Filtrele",
    minRating: "En Az Puan:",
    maxRating: "En \u00c7ok Puan:",
    all: "T\u00fcm\u00fc",
    today: "Bug\u00fcn",
    thisMonth: "Bu Ay",
    threeMonths: "3 Ay",
    thisYear: "Bu Y\u0131l",
    apply: "Uygula",
    reset: "S\u0131f\u0131rla",
    searchEntries: "Kay\u0131tlarda ara...",
    loadingEntries: "Kay\u0131tlar y\u00fckleniyor...",
    untitled: "Ba\u015fl\u0131ks\u0131z",
    noNotesYet: "Hen\u00fcz not yok.",
    details: "Detaylar",
    deleteEntry: "Kay\u0131t silinsin mi?",
    deleteEntryDescription: "Bu kay\u0131t kal\u0131c\u0131 olarak silinecek.",
    cancel: "Vazge\u00e7",
    delete: "Sil",
    deleting: "Siliniyor...",
    entryIdMissing: "Kay\u0131t kimli\u011fi eksik.",
    rate: "Puan",
    edit: "D\u00fczenle",
    userName: "Kullan\u0131c\u0131 Ad\u0131",
    logOut: "\u00c7\u0131k\u0131\u015f Yap",
    stats: "\u0130statistikler",
    loadingStats: "\u0130statistikler y\u00fckleniyor...",
    loginBeforeProfilePicture: "Profil foto\u011fraf\u0131 eklemeden \u00f6nce giri\u015f yapmal\u0131s\u0131n.",
    profilePicturePermissionRequired: "Profil foto\u011fraf\u0131 eklemek i\u00e7in medya k\u00fct\u00fcphanesi izni gerekiyor.",
    profilePictureProcessError: "Se\u00e7ilen profil foto\u011fraf\u0131 i\u015flenemedi.",
    profilePictureSaveError: "Se\u00e7ilen profil foto\u011fraf\u0131 kaydedilemedi.",
    profileMostUsedEntryType: "En \u00c7ok Kullan\u0131lan Kay\u0131t T\u00fcr\u00fc",
    profileEntriesAddedThisWeek: "Bu Hafta Eklenen Kay\u0131tlar",
    profileCurrentStreak: "G\u00fcncel Seri",
    profileLongestStreakEver: "En Uzun Seri",
    profileAverageRating: "Ortalama Puan",
    profileTotalNumberOfEntries: "Toplam Kay\u0131t Say\u0131s\u0131",
    profileTotalEntriesThisMonth: "Bu Ayki Toplam Kay\u0131tlar",
    profileEntriesAddedToday: "Bug\u00fcn Eklenen Kay\u0131tlar",
    profileMostFrequentlyUsedRating: "En S\u0131k Kullan\u0131lan Puan",
    profileHighestRatedCategory: "En Y\u00fcksek Puanl\u0131 Kategori",
    entryTypeMovie: "Film",
    entryTypeSeries: "Dizi",
    entryTypeDocumentary: "Belgesel",
    entryTypeAnime: "Anime",
    entryTypeMusic: "M\u00fczik",
    entryTypePodcast: "Podcast",
    entryTypeConcert: "Konser",
    entryTypeTheatre: "Tiyatro",
    entryTypeOpera: "Opera",
    entryTypeBallet: "Bale",
    entryTypeStandUp: "Stand-up",
    entryTypeMatch: "Ma\u00e7",
    entryTypeGaming: "Oyun",
    entryTypeBook: "Kitap",
    entryTypeBlog: "Blog",
    entryTypeExhibition: "Sergi",
    entryTypeFestival: "Festival",
    entryTypeOther: "Di\u011fer",
  },
};

const entryTypeKeys = {
  Movie: "entryTypeMovie",
  Series: "entryTypeSeries",
  Documentary: "entryTypeDocumentary",
  Anime: "entryTypeAnime",
  Music: "entryTypeMusic",
  Podcast: "entryTypePodcast",
  Concert: "entryTypeConcert",
  Theatre: "entryTypeTheatre",
  Opera: "entryTypeOpera",
  Ballet: "entryTypeBallet",
  "Stand-up": "entryTypeStandUp",
  Match: "entryTypeMatch",
  Gaming: "entryTypeGaming",
  Book: "entryTypeBook",
  Blog: "entryTypeBlog",
  Exhibition: "entryTypeExhibition",
  Festival: "entryTypeFestival",
  Other: "entryTypeOther",
};

const i18n = new I18n(translations);
i18n.defaultLocale = "en";
i18n.locale = "en";
i18n.enableFallback = true;

const listeners = new Set();

function notifyLanguageChange() {
  listeners.forEach((listener) => listener());
}

export function setLanguage(nextLanguage) {
  i18n.locale = nextLanguage === "tr" ? "tr" : "en";
  notifyLanguageChange();
}

export function toggleLanguage() {
  setLanguage(i18n.locale === "en" ? "tr" : "en");
}

export function t(key, params) {
  return i18n.t(key, params);
}

export function getEntryTypeLabel(type) {
  const key = entryTypeKeys[type];
  return key ? t(key) : type;
}

export function useLanguage() {
  const [language, setLanguageState] = useState(i18n.locale);

  useEffect(() => {
    function rerender() {
      setLanguageState(i18n.locale);
    }

    listeners.add(rerender);
    return () => {
      listeners.delete(rerender);
    };
  }, []);

  return {
    language,
    setLanguage,
    toggleLanguage,
    t,
    getEntryTypeLabel,
  };
}
